version: '3.3'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-clothes-fe-nextjs
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    expose:
      - "3000"

  # nginx:
  #   image: nginx:alpine
  #   container_name: ai-clothes-fe-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/conf.d:/etc/nginx/conf.d:ro
  #     - ./nginx/certbot/conf:/etc/letsencrypt:ro
  #     - ./nginx/certbot/www:/var/www/certbot:ro
  #     - ./nginx/logs:/var/log/nginx
  #   depends_on:
  #     - nextjs-app

networks:
  default:
    driver: bridge

