version: '3.3'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-clothes-fe-nextjs
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    expose:
      - "3000"

networks:
  default:
    driver: bridge

