import { Card, CardContent, CardDescription, CardHeader } from "@/components/ui/card"
import { Star } from "lucide-react"

const testimonials = [
  {
    name: "Sarah Chen",
    role: "Fashion Designer",
    content:
      "This AI platform has revolutionized my design process. I can now turn any inspiration into wearable art in minutes!",
    rating: 5,
    avatar: "/professional-woman-fashion-designer.jpg",
  },
  {
    name: "Marcus Rodriguez",
    role: "Boutique Owner",
    content:
      "The quality and uniqueness of designs generated by this AI is incredible. My customers love the custom pieces.",
    rating: 5,
    avatar: "/professional-man-boutique-owner.jpg",
  },
  {
    name: "Emma Thompson",
    role: "Fashion Enthusiast",
    content: "I never thought I could create my own clothing designs. This platform made it so easy and fun!",
    rating: 5,
    avatar: "/young-woman-fashion-enthusiast.png",
  },
]

export function TestimonialsSection() {
  return (
    <section className="py-20 bg-muted/30">
      <div className="container mx-auto px-4">
        <div className="text-center space-y-4 mb-16">
          <h2 className="text-3xl lg:text-5xl font-bold text-balance">
            {"What Our "}
            <span className="text-primary">{"Creators Say"}</span>
          </h2>
          <p className="text-xl text-muted-foreground text-pretty max-w-3xl mx-auto">
            {
              "Join thousands of satisfied designers and fashion enthusiasts who are creating amazing pieces with our AI"
            }
          </p>
        </div>

        <div className="grid md:grid-cols-3 gap-8">
          {testimonials.map((testimonial, index) => (
            <Card key={index} className="border-border hover:shadow-lg transition-shadow duration-300">
              <CardHeader className="space-y-4">
                <div className="flex items-center space-x-1">
                  {[...Array(testimonial.rating)].map((_, i) => (
                    <Star key={i} className="h-5 w-5 fill-accent text-accent" />
                  ))}
                </div>
                <CardDescription className="text-foreground text-base leading-relaxed">
                  {`"${testimonial.content}"`}
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center space-x-4">
                  <img
                    src={testimonial.avatar || "/placeholder.svg"}
                    alt={testimonial.name}
                    className="h-12 w-12 rounded-full object-cover"
                  />
                  <div>
                    <div className="font-semibold text-foreground">{testimonial.name}</div>
                    <div className="text-sm text-muted-foreground">{testimonial.role}</div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  )
}
